/**
 * Feature registry — source of truth for product areas (governance + audits).
 * Update when adding a major feature; run npm run audit:features to validate wiring.
 */

/** @typedef {{ id: string, name: string, layer: string, ui: string[], engines: string[], hooks: string[], notes?: string }} FeatureDef */

/** @type {FeatureDef[]} */
export const FEATURES = [
  {
    id: "home-dashboard",
    name: "Home dashboard",
    layer: "product",
    ui: ["ui/features/pages/HomePage.jsx", "ui/features/dashboard/"],
    engines: ["engines/stabilityPlan.js", "engines/survival.js", "engines/burden.js", "engines/forecast.js"],
    hooks: ["hooks/useStabilityIntel.js", "hooks/useCommitIntel.js"],
  },
  {
    id: "commitments",
    name: "Bills & commitments",
    layer: "product",
    ui: ["ui/features/pages/CommitmentsPage.jsx", "ui/features/modals/BillDetailModal.jsx", "ui/features/modals/CommitmentEditModal.jsx"],
    engines: ["engines/reminders.js", "engines/forecastSeries.js"],
    hooks: ["hooks/useCommitIntel.js"],
  },
  {
    id: "lending",
    name: "Lending & trust",
    layer: "product",
    ui: [
      "ui/features/pages/AgreementsPage.jsx",
      "ui/features/agreements/",
      "ui/features/lending/",
      "ui/features/modals/LendingDetailModal.jsx",
    ],
    engines: ["engines/lendingTrust.js", "engines/lendingAgreement.js"],
    hooks: ["ui/features/lending/useLendingLists.js"],
    notes: "Agreements tab — informal lending + legal documents; legacy /money/lending redirects here",
  },
  {
    id: "net-worth",
    name: "Net worth & financial life intelligence",
    layer: "product",
    ui: [
      "ui/features/profile/hub/ProfileFinancialHero.jsx",
      "ui/features/profile/ProfileNetWorthSection.jsx",
      "ui/features/netWorth/",
    ],
    engines: [
      "engines/netWorth/core.js",
      "engines/netWorth/liquidity.js",
      "engines/netWorth/debtHealth.js",
      "engines/netWorth/lifeScore.js",
      "engines/netWorth/pressureWealth.js",
      "engines/netWorth/insights.js",
      "engines/netWorth/simulation.js",
    ],
    hooks: ["hooks/useNetWorthIntel.js"],
    notes: "Integrates commitments, lending, and wealth entries for life-position intelligence",
  },
  {
    id: "analytics",
    name: "Analytics",
    layer: "product",
    ui: ["ui/features/pages/AnalyticsPage.jsx", "ui/features/analytics/"],
    engines: ["engines/analyticsSeries.js", "engines/salaryBreakdown.js"],
    hooks: [],
  },
  {
    id: "calculators",
    name: "Dashboard calculators",
    layer: "product",
    ui: ["ui/features/dashboard/DashboardTools.jsx", "ui/features/tools/"],
    engines: [
      "engines/affordability.js",
      "engines/loanPayoffTiming.js",
      "engines/chitFund.js",
      "engines/bondAnalyzer.js",
      "engines/quickScenarios.js",
      "engines/incomeTaxEstimate.js",
      "engines/epfTracker.js",
      "engines/ppfTracker.js",
      "engines/npsPlanner.js",
      "engines/gratuityEstimate.js",
      "engines/sipAdvisor.js",
      "engines/insuranceCalculator.js",
    ],
    hooks: [],
  },
  {
    id: "profile",
    name: "Profile & settings",
    layer: "product",
    ui: [
      "ui/features/pages/ProfilePage.jsx",
      "ui/features/pages/ProfileScoresDetailPage.jsx",
      "ui/features/profile/ProfileCloudSyncSection.jsx",
      "ui/features/profile/ProfileSecuritySection.jsx",
      "ui/features/profile/hub/ProfileFinancialHero.jsx",
      "ui/features/profile/",
    ],
    engines: [],
    hooks: ["hooks/useProfileScoreGuide.js"],
    notes: "Auth via services/supabase; cloud backup via services/sync; scores detail at /profile/scores",
  },
  {
    id: "notifications",
    name: "Notifications & reminders",
    layer: "platform",
    ui: ["ui/features/NotificationPanel.jsx"],
    engines: ["engines/notifications.js", "engines/reminders.js"],
    hooks: [],
  },
  {
    id: "onboarding",
    name: "Onboarding",
    layer: "platform",
    ui: ["ui/features/pages/OnboardingPage.jsx"],
    engines: [],
    hooks: [],
  },
  {
    id: "admin-intelligence",
    name: "Admin dashboard (internal)",
    layer: "platform",
    ui: [
      "ui/features/pages/AdminPage.jsx",
      "ui/features/admin/",
      "ui/admin/AdminFloatingButton.jsx",
    ],
    engines: [],
    hooks: ["hooks/useAdminOverview.js"],
    notes: "Requires profiles.is_admin; FAB on left for admins only; route /admin",
  },
  {
    id: "goals",
    name: "Financial goals",
    layer: "product",
    ui: ["ui/features/tools/GoalsToolPanel.jsx"],
    engines: ["engines/goalsProgress.js", "engines/goalBalance.js"],
    hooks: [],
  },
  {
    id: "variable-spend",
    name: "Variable spend logging",
    layer: "product",
    ui: [
      "ui/features/modals/LogSpendModal.jsx",
      "ui/features/commitments/DailySpendPanel.jsx",
      "ui/features/analytics/MonthlySpendAnalyticsSection.jsx",
    ],
    engines: ["engines/transactionIntel.js", "engines/smsToTransaction.js"],
    hooks: [],
  },
  {
    id: "bank-import",
    name: "Bank statement import",
    layer: "product",
    ui: ["ui/features/modals/BankStatementImportModal.jsx"],
    engines: ["engines/bankStatementParser.js"],
    hooks: [],
    notes: "Pro tier — bank_import gate",
  },
  {
    id: "sms-detect",
    name: "SMS spend & bill detection",
    layer: "product",
    ui: ["ui/features/modals/SmsDetectModal.jsx", "ui/features/modals/SpendSmsDetectModal.jsx"],
    engines: ["engines/smsParser.js", "engines/smsCommitmentMatcher.js", "engines/smsToTransaction.js"],
    hooks: [],
    notes: "Client-side SMS paste; services/smsAutoDetect.js for automation hooks",
  },
  {
    id: "payments",
    name: "Payment recording & calendar",
    layer: "product",
    ui: [
      "ui/features/commitments/CommitmentsPaymentModal.jsx",
      "ui/features/dashboard/PaymentDeadlineCalendarModal.jsx",
    ],
    engines: ["engines/cashflowCalendar.js"],
    hooks: [],
  },
  {
    id: "lending-recovery",
    name: "Lending recovery & overdue notices",
    layer: "product",
    ui: ["ui/features/pages/AgreementsPage.jsx", "ui/features/lending/"],
    engines: ["engines/lendingRecovery.js", "engines/lendingMonthCash.js"],
    hooks: [],
  },
  {
    id: "subscription-leak",
    name: "Subscription leak detection",
    layer: "product",
    ui: ["ui/features/dashboard/FinancialPulseCard.jsx"],
    engines: ["engines/subscriptionLeak.js"],
    hooks: [],
    notes: "Subscription insights in Financial Pulse tips — Pro tier subscription_leak",
  },
  {
    id: "ai-advisor",
    name: "AI financial advisor",
    layer: "product",
    ui: ["ui/features/tools/FinancialAdvisorTool.jsx"],
    engines: [],
    hooks: [],
    notes: "Pro tier — Supabase Edge Function proxy; local regex fallback offline",
  },
  {
    id: "paycheck",
    name: "Paycheck & salary timing",
    layer: "product",
    ui: [
      "ui/features/analytics/PaycheckBreakdown.jsx",
      "ui/features/dashboard/CashflowCalendarStrip.jsx",
    ],
    engines: ["engines/salaryBreakdown.js", "engines/cashflowCalendar.js"],
    hooks: [],
  },
  {
    id: "bill-health",
    name: "Per-bill health scores",
    layer: "product",
    ui: ["ui/patterns/BillCard.jsx"],
    engines: ["engines/billHealth.js"],
    hooks: ["hooks/useStabilityIntel.js"],
  },
  {
    id: "ca-export",
    name: "CA-ready summary export",
    layer: "product",
    ui: ["ui/features/profile/ProfileBackupSection.jsx"],
    engines: ["engines/caExport.js"],
    hooks: [],
    notes: "Power tier — ca_share gate",
  },
  {
    id: "net-worth-milestones",
    name: "Net worth milestones",
    layer: "product",
    ui: ["ui/features/netWorth/"],
    engines: ["engines/netWorth/milestones.js"],
    hooks: ["hooks/useNetWorthIntel.js"],
  },
];

export const FEATURE_IDS = FEATURES.map((f) => f.id);
