#!/usr/bin/env node
/**
 * scripts/zip.mjs
 * Creates perovo-reports.zip containing everything needed to
 * share the project. Excludes generated, secret, and large files.
 * Works on Windows, Mac, and Linux.
 *
 * Usage: npm run zip
 * Output: perovo-reports.zip in the project root
 */

import archiver from "archiver";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const OUTPUT = path.join(ROOT, "perovo-reports.zip");

// ── Folders/files to EXCLUDE ─────────────────────────────────
// Edit this list if you add new generated/secret folders.
const EXCLUDE_DIRS = new Set([
  "node_modules",
  "android",
  "ios",
  "releases",
  "dist",
  "dist-ota",
  "dist-ota-test",
  "dist-ota-verify",
  "dist-ssr",
  "dev-dist",
  ".git",
  ".cursor",
  ".vscode",
]);

const EXCLUDE_FILES = new Set([
  ".env",
  ".env.razorpay",
  "eslint-report.json",
  "perovo-reports.zip",
  "package-lock.json", // large, regenerated by npm install
]);

const EXCLUDE_EXTENSIONS = new Set([
  ".zip",
  ".apk",
  ".aab",
  ".keystore",
  ".jks",
  ".pfx",
  ".p12",
  ".pem",
  ".key",
]);

const EXCLUDE_DIRS_PARTIAL = [
  "supabase/.temp", // Supabase CLI cache
  "supabase/.branches", // Supabase local branches
  ".capacitor",
];

// ── Build the zip ─────────────────────────────────────────────
if (fs.existsSync(OUTPUT)) fs.unlinkSync(OUTPUT);

const output = fs.createWriteStream(OUTPUT);
const archive = archiver("zip", { zlib: { level: 6 } });

let fileCount = 0;

archive.on("entry", () => {
  fileCount++;
});
archive.on("warning", (err) => {
  if (err.code !== "ENOENT") throw err;
});
archive.on("error", (err) => {
  throw err;
});

output.on("close", () => {
  const mb = (archive.pointer() / 1024 / 1024).toFixed(1);
  console.log(`\n✓ perovo-reports.zip`);
  console.log(`  ${fileCount} files · ${mb} MB`);
  console.log(`  Ready to share.\n`);
});

archive.pipe(output);

// Walk the root directory
function shouldExclude(relPath) {
  const parts = relPath.split(path.sep);
  const name = parts[parts.length - 1];
  const ext = path.extname(name).toLowerCase();

  // Top-level dir excluded?
  if (parts.length === 1 && EXCLUDE_DIRS.has(parts[0])) return true;

  // Any segment is an excluded dir?
  for (const part of parts.slice(0, -1)) {
    if (EXCLUDE_DIRS.has(part)) return true;
  }

  // Partial path match (e.g. supabase/.temp)
  const normalised = relPath.replace(/\\/g, "/");
  for (const p of EXCLUDE_DIRS_PARTIAL) {
    if (normalised.startsWith(p + "/") || normalised === p) return true;
  }

  // File-level exclusions
  if (EXCLUDE_FILES.has(name)) return true;
  if (EXCLUDE_EXTENSIONS.has(ext)) return true;

  // Hidden files starting with . are OK (keep .gitignore, .env.example)
  // but skip .DS_Store and similar
  if (name === ".DS_Store" || name === "Thumbs.db") return true;

  return false;
}

function addDirectory(dirPath, zipPath) {
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    const relPath = path.join(zipPath, entry.name);
    if (shouldExclude(relPath)) continue;
    if (entry.isDirectory()) {
      addDirectory(fullPath, relPath);
    } else {
      archive.file(fullPath, { name: relPath });
    }
  }
}

console.log("Creating perovo-reports.zip...");
addDirectory(ROOT, "");
archive.finalize();
