import {
  ArrowsClockwise,
  Backpack,
  Bank,
  Bell,
  Book,
  BookOpen,
  Briefcase,
  Bus,
  Calculator,
  Calendar,
  Car,
  ChartBar,
  ChartLineDown,
  ChartLineUp,
  ChatCircle,
  Check,
  ClipboardText,
  Cloud,
  Coin,
  Coins,
  CreditCard,
  CurrencyInr,
  DeviceMobile,
  FileText,
  FirstAid,
  ForkKnife,
  Handshake,
  Hourglass,
  House,
  Laptop,
  Lightning,
  Lock,
  NotePencil,
  Package,
  Palette,
  PushPin,
  Receipt,
  Scroll,
  Shield,
  ShoppingCart,
  Television,
  User,
  UserCircle,
  Users,
  UsersThree,
  Wallet,
  Warning,
  Wrench,
} from "@phosphor-icons/react";
import { cn } from "../utils/cn.js";

/** @type {Record<string, import('@phosphor-icons/react').Icon>} */
const ICON_REGISTRY = {
  "arrows-clockwise": ArrowsClockwise,
  backpack: Backpack,
  bank: Bank,
  bell: Bell,
  book: Book,
  "book-open": BookOpen,
  briefcase: Briefcase,
  bus: Bus,
  calculator: Calculator,
  calendar: Calendar,
  car: Car,
  "chart-bar": ChartBar,
  "chart-line-down": ChartLineDown,
  "chart-line-up": ChartLineUp,
  "chat-circle": ChatCircle,
  check: Check,
  "clipboard-text": ClipboardText,
  cloud: Cloud,
  coin: Coin,
  coins: Coins,
  "credit-card": CreditCard,
  "currency-inr": CurrencyInr,
  "device-mobile": DeviceMobile,
  "file-text": FileText,
  "first-aid": FirstAid,
  "fork-knife": ForkKnife,
  handshake: Handshake,
  hourglass: Hourglass,
  house: House,
  laptop: Laptop,
  lightning: Lightning,
  lock: Lock,
  "note-pencil": NotePencil,
  package: Package,
  palette: Palette,
  "push-pin": PushPin,
  receipt: Receipt,
  scroll: Scroll,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  television: Television,
  user: User,
  "user-circle": UserCircle,
  users: Users,
  "users-three": UsersThree,
  wallet: Wallet,
  warning: Warning,
  wrench: Wrench,
};

/**
 * Phosphor icon (Regular weight by default). Use semantic `name` keys — never emoji.
 * @param {{
 *   name: string,
 *   size?: number | string,
 *   weight?: import('@phosphor-icons/react').IconWeight,
 *   className?: string,
 * }} props
 */
export function CtIcon({ name, size = 20, weight = "regular", className = "" }) {
  const Icon = ICON_REGISTRY[name];
  if (!Icon) return null;
  return <Icon size={size} weight={weight} className={cn("ct-icon", className)} aria-hidden />;
}

export default CtIcon;
